### ISSUE TITLE
OutOfRangeError:Read fewer bytes than requested

### ISSUE THREAD

**Issue by chenting0324** [inikdom/rnn-speech#28]
Hello~When I run the code on my PC,the problem came as:OutOfRangeError:Read fewer bytes than requested
I don't konw how to solve it,and Can this code run in windows platform or only in Linux or MAC ?

**Comment by AMairesse** [comment]
Hi, I haven't tested it on a Windows or Mac platform so I can't tell but it should work.
Given your other opened issues I think this error message is related to the pre-trained model you are trying to use. If you don't use git-lfs you will not have the data file but only a text file containing information about the git-lfs link instead. When trying to open it the tensorflow function return this error because the file is invalid (too small).
